/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;


import entities.Users;
import static java.awt.SystemColor.menu;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import recog.FaceRecognizer;
import register.FaceTracker;

/**
 *
 * @author mobicash
 */
public class Register extends javax.swing.JFrame {
    public static javax.swing.JLabel myimage;  
    JMenu submenu;
    JMenuItem menuItem;
     int usersID ;

   
    /**
     * Creates new form Register
     */
    public static boolean savenow;
    public Register() {
       
        initComponents();
          
        buttonGroup1.add(radio_male);
        buttonGroup1.add(radio_female);
        error_lable.setVisible(false);
        myimage = imagefieldicon;
        savenow =false;
      
        menuItem = new JMenuItem("Verify users",
                         new ImageIcon(getClass().getResource("/verify.png")));
        menuItem.setMnemonic(KeyEvent.VK_B);
        
        jMenu2.add(menuItem);
       menuItem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
             new FaceRecognizer();   
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        secondname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        idnum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        radio_male = new javax.swing.JRadioButton();
        radio_female = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        imagefieldicon = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        registration = new javax.swing.JButton();
        addimage_but = new javax.swing.JButton();
        error_lable = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(190, 190, 190));

        jPanel1.setBackground(new java.awt.Color(196, 196, 196));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("First Name");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Second Name");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Phone number");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Id number");

        radio_male.setText("Male");

        radio_female.setText("Female");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Gender");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5))
                            .addGap(46, 46, 46)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(secondname, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idnum, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(radio_male)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radio_female)))))
                    .addComponent(jLabel4))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(secondname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radio_female, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radio_male, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        imagefieldicon.setBackground(new java.awt.Color(196, 196, 196));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagefieldicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagefieldicon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        registration.setText("Register");
        registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationActionPerformed(evt);
            }
        });

        addimage_but.setText("Add image");
        addimage_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addimage_butActionPerformed(evt);
            }
        });

        error_lable.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        error_lable.setForeground(new java.awt.Color(245, 27, 8));
        error_lable.setText("Wrong words added you niga");

        jMenu2.setText("Verify");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Search");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(242, 242, 242)
                                .addComponent(registration))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 186, Short.MAX_VALUE)
                                .addComponent(addimage_but))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(error_lable)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(registration)
                    .addComponent(addimage_but))
                .addGap(18, 18, 18)
                .addComponent(error_lable)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addimage_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addimage_butActionPerformed
        // TODO add your handling code here:
        EntityManager entityManager = Persistence.createEntityManagerFactory("FaceRecognitionPU").createEntityManager();
          int num = ((List)entityManager.createNamedQuery("Users.findAll").getResultList()).size();
          usersID = num+1;
          System.out.println("num==="+usersID);
          entityManager.getTransaction().begin();
        
        if(firstname.getText().toString().equalsIgnoreCase("")){
            error_lable.setVisible(true); 
             error_lable.setText("First name required");
        }else if(secondname.getText().toString().equalsIgnoreCase("")){
           error_lable.setVisible(true); 
             error_lable.setText("Second name required"); 
        }
        else if(phone.getText().toString().equalsIgnoreCase("")){
         error_lable.setVisible(true); 
             error_lable.setText("Mobile required");           }
        else if(idnum.getText().toString().equalsIgnoreCase("")){
           error_lable.setVisible(true); 
             error_lable.setText("ID number required"); 
        }
        else if(!radio_female.isSelected()&&!radio_male.isSelected()){
            error_lable.setVisible(true); 
             error_lable.setText("Gender required");
        }else {
             error_lable.setVisible(false); 
        new FaceTracker(usersID+"_"+firstname.getText().toString()+"_"+secondname.getText().toString(),imagefieldicon);
        }
        
    }//GEN-LAST:event_addimage_butActionPerformed

    private void registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationActionPerformed
            EntityManager entityManager = Persistence.createEntityManagerFactory("FaceRecognitionPU").createEntityManager();
          int num = ((List)entityManager.createNamedQuery("Users.findAll").getResultList()).size();
          usersID = num+1;
          System.out.println("num==="+usersID);
          entityManager.getTransaction().begin();
        
        if(firstname.getText().toString().equalsIgnoreCase("")){
            error_lable.setVisible(true); 
             error_lable.setText("First name required");
        }else if(secondname.getText().toString().equalsIgnoreCase("")){
           error_lable.setVisible(true); 
             error_lable.setText("Second name required"); 
        }
        else if(phone.getText().toString().equalsIgnoreCase("")){
         error_lable.setVisible(true); 
             error_lable.setText("Mobile required");           }
        else if(idnum.getText().toString().equalsIgnoreCase("")){
           error_lable.setVisible(true); 
             error_lable.setText("ID number required"); 
        }
        else if(!radio_female.isSelected()&&!radio_male.isSelected()){
            error_lable.setVisible(true); 
             error_lable.setText("Gender required");
        }else if(!savenow){
            System.out.println("savenow ="+savenow);
            error_lable.setVisible(true); 
             error_lable.setText("Add image of user"); 
        }
        else {
           
            Users c = new Users();
            c.setName(firstname.getText().toString()+" "+secondname.getText().toString());
            c.setMobile(phone.getText().toString());
            c.setId(usersID);
            if(radio_female.isSelected()){
              c.setSex("Female");
             }else{
              c.setSex("Male");   
             }
            c.setStatus(idnum.getText().toString());
            entityManager.persist(c);
            entityManager.getTransaction().commit(); 
           if (entityManager.contains(c)) {
             JFrame frame = new JFrame("Success");
       Object[] options = {"Ok"};
    int n = JOptionPane.showOptionDialog(frame, "User successfully saved", "Success",
    JOptionPane.YES_NO_CANCEL_OPTION,
    JOptionPane.QUESTION_MESSAGE,
    null,
    options,null);
    if(n==0){
        System.out.println("==ok=="); 
        firstname.setText("");
        secondname.setText("");
        phone.setText("");
        idnum.setText("");
       imagefieldicon.setIcon(null);
        savenow =false;
       
    }else if(n==1){
       
    }else{
        
         System.out.println("==don't know==");  
    }  
           }
            
            
            
            
            //new FaceRecognizer();
            /* bean = new Dbclass();
             error_lable.setVisible(false); 
             Clients client = new Clients();
             client.setFirstname(firstname.getText().toString());
             client.setSecondname(secondname.getText().toString());
             client.setPhone(phone.getText().toString());
             client.setIdnumber(idnum.getText().toString());
             if(radio_female.isSelected()){
              client.setGender("Female");
             }else{
              client.setGender("Male");   
             }
             controller = new ClientsJpaController(Dbclass.getEntityManagerFactory());
          try {
              controller.create(client);
              // if (bean.create(client) != null)
                JOptionPane.showMessageDialog(null,
                 "New person created successfully.");
          } catch (Exception ex) {
              Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
          }
       */
        }
        
       
    }//GEN-LAST:event_registrationActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        new FaceRecognizer();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        firstname.setText("");
        secondname.setText("");
        phone.setText("");
        idnum.setText("");
        imagefieldicon.setIcon(null);
        savenow =false;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new Register().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addimage_but;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel error_lable;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField idnum;
    private javax.swing.JLabel imagefieldicon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField phone;
    private javax.swing.JRadioButton radio_female;
    private javax.swing.JRadioButton radio_male;
    private javax.swing.JButton registration;
    private javax.swing.JTextField secondname;
    // End of variables declaration//GEN-END:variables

public void updateimage(String name,javax.swing.JLabel image){
    System.out.println("image==="+name);
   //  imagefield.setIcon(new javax.swing.ImageIcon(FaceTracker.class.getResource("/trainingImages/andy_kuts0.png")));
    image.setIcon(new javax.swing.ImageIcon(Register.class.getResource("/trainingImages/"+name+"0.png")));
       savenow=true;
}

}
