/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import entities.Users;
import java.awt.Point;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.LineBorder;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;

/**
 *
 * @author mobicash
 */
public class UserDetails extends javax.swing.JFrame {
    
   Users usersDetails;
  static int DBuserid;
  EntityManager entityManager;

    /**
     * Creates new form UserDetails
     */
    public UserDetails(int userID) {
        this.DBuserid = userID;
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           addWindowListener( new WindowAdapter() {
      public void windowClosing(WindowEvent e)
      { 
          dispose();
          //facePanel.closeDown();    // stop snapping pics
       // System.exit(0);
      }
    });
           pack();  
    setResizable(false);
    setVisible(true);
    SwingUtilities.invokeLater(new Runnable() {
      public void run()
      {
        Point p = new Point(0, 0);
        SwingUtilities.convertPointToScreen(p, getContentPane());
        Point l = getLocation();
        l.x -= p.x;
        l.y -= p.y;
        setLocation(l);
      }
    });
        
      panaldetails.setBorder(new LineBorder(java.awt.Color.DARK_GRAY, 2, true));
        panalimage.setBorder(new LineBorder(null, 5, true));
        error_label.setVisible(false);
        
        paydetails_panal.setBorder(new LineBorder(java.awt.Color.DARK_GRAY, 2, true));
        pay_image_panal.setBorder(new LineBorder(null, 5, true));
        
        System.out.println("====userid==="+DBuserid);
        entityManager = Persistence.createEntityManagerFactory("FaceRecogPU").createEntityManager();
          usersDetails = ((Users)entityManager.createNamedQuery("Users.findById")
                  .setParameter("id", DBuserid).getSingleResult());
          System.out.println("mobile==="+usersDetails.getMobile());
          entityManager.getTransaction().begin();
          
          name.setText(usersDetails.getName());
          mobile.setText(usersDetails.getMobile());
          userid.setText(usersDetails.getStatus());
          gender.setText(usersDetails.getSex());
          String img =DBuserid+"_"+usersDetails.getName().replace(" ", "_");
          details_image.setIcon(new javax.swing.ImageIcon(Register.class.getResource("/trainingImages/"+img+"2.png")));
          pay_image.setIcon(new javax.swing.ImageIcon(Register.class.getResource("/trainingImages/"+img+"2.png")));
          if(usersDetails.getPaid()!=null && usersDetails.getPaid()){
             error_label.setText("User already received payments");
            error_label.setVisible(true);
            amount_edit.setFocusable(false);
            amount_edit.setText(usersDetails.getAmount().toString());
            
          }
          
          PlainDocument doc = (PlainDocument) amount_edit.getDocument();
      doc.setDocumentFilter(new MyIntFilter());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientInfoPane = new javax.swing.JTabbedPane();
        personalPanel = new javax.swing.JPanel();
        panalimage = new javax.swing.JPanel();
        details_image = new javax.swing.JLabel();
        panaldetails = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        userid = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        contactPanel = new javax.swing.JPanel();
        pay_image_panal = new javax.swing.JPanel();
        pay_image = new javax.swing.JLabel();
        paydetails_panal = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        amount_edit = new javax.swing.JTextField();
        error_label = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        clientInfoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personalPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panalimage.setBackground(new java.awt.Color(190, 190, 190));

        javax.swing.GroupLayout panalimageLayout = new javax.swing.GroupLayout(panalimage);
        panalimage.setLayout(panalimageLayout);
        panalimageLayout.setHorizontalGroup(
            panalimageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panalimageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(details_image, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        panalimageLayout.setVerticalGroup(
            panalimageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(details_image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panaldetails.setBackground(new java.awt.Color(190, 190, 190));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jLabel1.setText("Name");

        name.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jLabel4.setText("Mobile");

        mobile.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jLabel6.setText("User ID");

        userid.setText("jLabel10");

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jLabel11.setText("Gender");

        gender.setText("jLabel12");

        javax.swing.GroupLayout panaldetailsLayout = new javax.swing.GroupLayout(panaldetails);
        panaldetails.setLayout(panaldetailsLayout);
        panaldetailsLayout.setHorizontalGroup(
            panaldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panaldetailsLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panaldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addGap(50, 50, 50)
                .addGroup(panaldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gender)
                    .addComponent(mobile)
                    .addComponent(name)
                    .addComponent(userid))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        panaldetailsLayout.setVerticalGroup(
            panaldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panaldetailsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panaldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panaldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mobile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panaldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(userid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panaldetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(gender))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout personalPanelLayout = new javax.swing.GroupLayout(personalPanel);
        personalPanel.setLayout(personalPanelLayout);
        personalPanelLayout.setHorizontalGroup(
            personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panalimage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(panaldetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        personalPanelLayout.setVerticalGroup(
            personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panalimage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panaldetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        clientInfoPane.addTab("User details", personalPanel);

        contactPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pay_image_panal.setBackground(new java.awt.Color(190, 190, 190));

        javax.swing.GroupLayout pay_image_panalLayout = new javax.swing.GroupLayout(pay_image_panal);
        pay_image_panal.setLayout(pay_image_panalLayout);
        pay_image_panalLayout.setHorizontalGroup(
            pay_image_panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pay_image_panalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pay_image, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pay_image_panalLayout.setVerticalGroup(
            pay_image_panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pay_image_panalLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pay_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        paydetails_panal.setBackground(new java.awt.Color(190, 190, 190));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setText("Amount ");

        error_label.setBackground(new java.awt.Color(242, 240, 240));
        error_label.setFont(new java.awt.Font("UnGungseo", 2, 12)); // NOI18N
        error_label.setForeground(java.awt.Color.red);
        error_label.setText("User already been paid");

        jButton4.setText("Pay");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paydetails_panalLayout = new javax.swing.GroupLayout(paydetails_panal);
        paydetails_panal.setLayout(paydetails_panalLayout);
        paydetails_panalLayout.setHorizontalGroup(
            paydetails_panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paydetails_panalLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addGroup(paydetails_panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paydetails_panalLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(paydetails_panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(error_label)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paydetails_panalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amount_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paydetails_panalLayout.setVerticalGroup(
            paydetails_panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paydetails_panalLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(paydetails_panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(amount_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(error_label)
                .addGap(32, 32, 32)
                .addComponent(jButton4)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contactPanelLayout = new javax.swing.GroupLayout(contactPanel);
        contactPanel.setLayout(contactPanelLayout);
        contactPanelLayout.setHorizontalGroup(
            contactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactPanelLayout.createSequentialGroup()
                .addComponent(pay_image_panal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(paydetails_panal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contactPanelLayout.setVerticalGroup(
            contactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pay_image_panal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paydetails_panal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        clientInfoPane.addTab("Pay User", contactPanel);

        clientInfoLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        clientInfoLabel.setText("User Details:"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(clientInfoLabel)
                        .addComponent(clientInfoPane, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(43, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(clientInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                    .addComponent(clientInfoPane, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(usersDetails.getPaid()!=null && usersDetails.getPaid()){
            error_label.setText("User already received payments");
            error_label.setVisible(true);
            amount_edit.setFocusable(false);

            JFrame frame = new JFrame("Error");
            JOptionPane.showMessageDialog(frame,
                usersDetails.getName()+" has already been paid",
                "Payment Error",
                JOptionPane.ERROR_MESSAGE);

        }else{
            if(amount_edit.getText().toString().length()<2){
                error_label.setText("Add some money to pay");
                error_label.setVisible(true);

            }else{
                error_label.setVisible(false);
                //entityManager.getTransaction().begin();
                usersDetails.setPaid(Boolean.TRUE);
                usersDetails.setAmount(Double.valueOf(amount_edit.getText().toString()));
                usersDetails.setTime(Double.valueOf(System.currentTimeMillis()));
                entityManager.persist(usersDetails);
                entityManager.getTransaction().commit();
                if (entityManager.contains(usersDetails)) {
                    JFrame frame = new JFrame("Success");
                    JOptionPane.showMessageDialog(frame,
                        usersDetails.getName()+" has been paid",
                        "Payment Success",
                        JOptionPane.INFORMATION_MESSAGE);
                }

            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDetails(4).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount_edit;
    private javax.swing.JLabel clientInfoLabel;
    private javax.swing.JTabbedPane clientInfoPane;
    private javax.swing.JPanel contactPanel;
    private javax.swing.JLabel details_image;
    private javax.swing.JLabel error_label;
    private javax.swing.JLabel gender;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel mobile;
    private javax.swing.JLabel name;
    private javax.swing.JPanel panaldetails;
    private javax.swing.JPanel panalimage;
    private javax.swing.JLabel pay_image;
    private javax.swing.JPanel pay_image_panal;
    private javax.swing.JPanel paydetails_panal;
    private javax.swing.JPanel personalPanel;
    private javax.swing.JLabel userid;
    // End of variables declaration//GEN-END:variables



class MyIntFilter extends DocumentFilter {
   @Override
   public void insertString(DocumentFilter.FilterBypass fb, int offset, String string,
         AttributeSet attr) throws BadLocationException {

      Document doc = fb.getDocument();
      StringBuilder sb = new StringBuilder();
      sb.append(doc.getText(0, doc.getLength()));
      sb.insert(offset, string);

      if (test(sb.toString())) {
         super.insertString(fb, offset, string, attr);
      } else {
         // warn the user and don't allow the insert
      }
   }

   private boolean test(String text) {
      try {
         Integer.parseInt(text);
         return true;
      } catch (NumberFormatException e) {
         return false;
      }
   }

   @Override
   public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text,
         AttributeSet attrs) throws BadLocationException {

      Document doc = fb.getDocument();
      StringBuilder sb = new StringBuilder();
      sb.append(doc.getText(0, doc.getLength()));
      sb.replace(offset, offset + length, text);

      if (test(sb.toString())) {
         super.replace(fb, offset, length, text, attrs);
      } else {
         // warn the user and don't allow the insert
      }

   }

   @Override
   public void remove(DocumentFilter.FilterBypass fb, int offset, int length)
         throws BadLocationException {
      Document doc = fb.getDocument();
      StringBuilder sb = new StringBuilder();
      sb.append(doc.getText(0, doc.getLength()));
      sb.delete(offset, offset + length);

      if (test(sb.toString())) {
         super.remove(fb, offset, length);
      } else {
         // warn the user and don't allow the insert
      }

   }
}


}
